create table users
(
	id bigint generated by default as identity
		constraint users_pkey
			primary key,
	enabled boolean,
	username varchar(50) not null,
	password varchar(500) not null,
	authority varchar(50) not null
);

alter table users owner to postgres;

